package com.exe201.rrms.controller;
import com.exe201.rrms.entity.*; import com.exe201.rrms.repository.*; import com.exe201.rrms.service.*; import jakarta.servlet.http.HttpServletRequest; import org.springframework.web.bind.annotation.*; import java.time.*; import java.util.*;
@RestController @RequestMapping("/api/listings") public class ListingController { private final AuthService auth;private final ListingRepository listings;private final PropertyRepository props;private final ListingInterestRepository interests;private final FavoriteRepository favs;private final NotificationService noti; public ListingController(AuthService a,ListingRepository l,PropertyRepository p,ListingInterestRepository i,FavoriteRepository f,NotificationService n){auth=a;listings=l;props=p;interests=i;favs=f;noti=n;}
 @GetMapping("/mine") public List<Listing> mine(HttpServletRequest r){User u=auth.current(r);return listings.findByLandlordIdOrderByUpdatedAtDesc(u.getId());}
 @PostMapping public Map<String,Object> create(HttpServletRequest r,@RequestBody Map<String,Object>b){User u=auth.current(r);auth.requireRole(u,"LANDLORD","ADMIN","SUPER_ADMIN");Property p=new Property();apply(p,b);p.setLandlordId(u.getId());if(p.getContactPhone()==null||p.getContactPhone().isBlank())p.setContactPhone(u.getPhone());p=props.save(p);Listing l=new Listing();l.setPropertyId(p.getId());l.setLandlordId(u.getId());l.setTitle(Objects.toString(b.get("title"),p.getName()));l.setStatus(Objects.toString(b.get("listingStatus"),"DRAFT"));if("PENDING_REVIEW".equals(l.getStatus()))l.setFreshnessDueAt(LocalDateTime.now().plusDays(15));l=listings.save(l);return Map.of("property",p,"listing",l);}
 @PutMapping("/{id}") public Map<String,Object> update(@PathVariable Long id,HttpServletRequest r,@RequestBody Map<String,Object>b){User u=auth.current(r);Listing l=listings.findById(id).orElseThrow();owner(u,l);Property p=props.findById(l.getPropertyId()).orElseThrow();apply(p,b);props.save(p);if(b.get("title")!=null)l.setTitle(b.get("title").toString()); if(List.of("ACTIVE","PENDING_REVIEW","NEED_REVISION").contains(l.getStatus())){l.setStatus("PENDING_REVIEW");l.setRevisionNote("Thông tin đã thay đổi và cần kiểm duyệt lại");}listings.save(l);return Map.of("property",p,"listing",l);}
 @PostMapping("/{id}/submit") public Listing submit(@PathVariable Long id,HttpServletRequest r){User u=auth.current(r);Listing l=listings.findById(id).orElseThrow();owner(u,l);l.setStatus("PENDING_REVIEW");l.setRevisionNote(null);return listings.save(l);}
 @PostMapping("/{id}/confirm-availability") public Listing confirm(@PathVariable Long id,HttpServletRequest r,@RequestBody(required=false)Map<String,String>b){User u=auth.current(r);Listing l=listings.findById(id).orElseThrow();owner(u,l);Property p=props.findById(l.getPropertyId()).orElseThrow();p.setLastAvailabilityConfirmedAt(LocalDateTime.now());if(b!=null&&b.get("availability")!=null)p.setAvailability(b.get("availability"));props.save(p);l.setLastConfirmedAt(LocalDateTime.now());l.setFreshnessDueAt(l.getPackageUntil()!=null&&l.getPackageUntil().isAfter(LocalDateTime.now())?l.getPackageUntil().plusDays(15):LocalDateTime.now().plusDays(15));if("HIDDEN_STALE".equals(l.getStatus()))l.setStatus("ACTIVE");return listings.save(l);}
 @PostMapping("/{id}/archive") public Listing archive(@PathVariable Long id,HttpServletRequest r){User u=auth.current(r);Listing l=listings.findById(id).orElseThrow();owner(u,l);l.setStatus("ARCHIVED");l.setArchivedAt(LocalDateTime.now());return listings.save(l);}
 @PostMapping("/{id}/interest") public ListingInterest interest(@PathVariable Long id,HttpServletRequest r,@RequestBody(required=false)Map<String,Boolean>b){User u=auth.current(r);ListingInterest x=interests.findByListingIdAndUserId(id,u.getId()).orElseGet(ListingInterest::new);x.setListingId(id);x.setUserId(u.getId());x.setMatchingEnabled(b!=null&&Boolean.TRUE.equals(b.get("matchingEnabled")));x.setStatus("INTERESTED");x=interests.save(x);Listing l=listings.findById(id).orElseThrow();l.setInterestCount(interests.countByListingId(id));listings.save(l);return x;}
 @DeleteMapping("/{id}/interest") public void uninterest(@PathVariable Long id,HttpServletRequest r){User u=auth.current(r);interests.findByListingIdAndUserId(id,u.getId()).ifPresent(interests::delete);}
 @PostMapping("/{id}/favorite") public Map<String,Object> favorite(@PathVariable Long id,HttpServletRequest r){User u=auth.current(r);var ex=favs.findByListingIdAndUserId(id,u.getId());if(ex.isPresent()){favs.delete(ex.get());return Map.of("favorite",false);}Favorite f=new Favorite();f.setListingId(id);f.setUserId(u.getId());favs.save(f);return Map.of("favorite",true);}
 @GetMapping("/favorites") public List<Favorite> favorites(HttpServletRequest r){return favs.findByUserId(auth.current(r).getId());} @GetMapping("/interests") public List<ListingInterest> myInterests(HttpServletRequest r){return interests.findByUserId(auth.current(r).getId());}
 private void owner(User u,Listing l){if(!Objects.equals(l.getLandlordId(),u.getId())&&!List.of("ADMIN","SUPER_ADMIN","MODERATOR").contains(u.getRole()))throw new SecurityException("Không phải tin của bạn");}
 private void apply(Property p,Map<String,Object>b){p.setName(str(b,"name",p.getName()));p.setProvince(str(b,"province",p.getProvince()));p.setDistrict(str(b,"district",p.getDistrict()));p.setWard(str(b,"ward",p.getWard()));p.setStreet(str(b,"street",p.getStreet()));p.setLatitude(dbl(b,"latitude",p.getLatitude()));p.setLongitude(dbl(b,"longitude",p.getLongitude()));p.setPrice(lng(b,"price",p.getPrice()));p.setArea(dbl(b,"area",p.getArea()));p.setDeposit(lng(b,"deposit",p.getDeposit()));p.setElectricityPrice(lng(b,"electricityPrice",p.getElectricityPrice()));p.setWaterPrice(lng(b,"waterPrice",p.getWaterPrice()));p.setInternetPrice(lng(b,"internetPrice",p.getInternetPrice()));p.setParkingFee(lng(b,"parkingFee",p.getParkingFee()));p.setOtherFees(lng(b,"otherFees",p.getOtherFees()));p.setFurniture(str(b,"furniture",p.getFurniture()));p.setPropertyType(str(b,"propertyType",p.getPropertyType()));p.setPostType(str(b,"postType",p.getPostType()));p.setTotalRooms(integer(b,"totalRooms",p.getTotalRooms()));p.setAvailableRooms(integer(b,"availableRooms",p.getAvailableRooms()));p.setTotalFloors(integer(b,"totalFloors",p.getTotalFloors()));p.setFloorText(str(b,"floorText",p.getFloorText()));p.setMaxOccupants(integer(b,"maxOccupants",p.getMaxOccupants()));p.setNearestSchool(str(b,"nearestSchool",p.getNearestSchool()));p.setNearestSchoolDistanceKm(dbl(b,"nearestSchoolDistanceKm",p.getNearestSchoolDistanceKm()));p.setAmenities(str(b,"amenities",p.getAmenities()));p.setRules(str(b,"rules",p.getRules()));p.setContactPhone(str(b,"contactPhone",p.getContactPhone()));p.setContactZalo(str(b,"contactZalo",p.getContactZalo()));p.setDescription(str(b,"description",p.getDescription()));p.setImageUrl(str(b,"imageUrl",p.getImageUrl()));p.setAvailability(str(b,"availability",p.getAvailability()));}
 private String str(Map<String,Object>b,String k,String d){return b.get(k)==null?d:b.get(k).toString();} private Long lng(Map<String,Object>b,String k,Long d){try{return b.get(k)==null?d:Long.valueOf(b.get(k).toString());}catch(Exception e){return d;}} private Integer integer(Map<String,Object>b,String k,Integer d){try{return b.get(k)==null?d:Integer.valueOf(b.get(k).toString());}catch(Exception e){return d;}} private Double dbl(Map<String,Object>b,String k,Double d){try{return b.get(k)==null?d:Double.valueOf(b.get(k).toString());}catch(Exception e){return d;}}
}
