package com.exe201.rrms.service;
import com.exe201.rrms.entity.*; import com.exe201.rrms.repository.*; import com.exe201.rrms.util.PasswordUtil; import jakarta.servlet.http.HttpServletRequest; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service public class AuthService {
 private final UserRepository users; private final AuthSessionRepository sessions;
 public AuthService(UserRepository users,AuthSessionRepository sessions){this.users=users;this.sessions=sessions;}
 public User register(User u){ if(users.findByEmail(u.getEmail()).isPresent()) throw new IllegalArgumentException("Email đã tồn tại"); normalizeRole(u); if(!Set.of("TENANT","LANDLORD").contains(u.getRole())) u.setRole("TENANT"); u.setStatus("ACTIVE"); u.setPassword(PasswordUtil.hash(u.getPassword())); return users.save(u); }
 public Map<String,Object> login(String email,String password){ User u=users.findByEmail(email).orElseThrow(()->new IllegalArgumentException("Email hoặc mật khẩu không đúng")); if(!"ACTIVE".equals(u.getStatus())) throw new IllegalStateException("Tài khoản đang bị khóa"); if(!PasswordUtil.verify(password,u.getPassword())) throw new IllegalArgumentException("Email hoặc mật khẩu không đúng"); if(!u.getPassword().startsWith("pbkdf2$")){u.setPassword(PasswordUtil.hash(password));} u.setLastLoginAt(LocalDateTime.now()); normalizeRole(u); users.save(u); return issue(u); }
 public Map<String,Object> issue(User u){ AuthSession s=new AuthSession(); s.setToken(UUID.randomUUID().toString().replace("-","")+UUID.randomUUID().toString().replace("-","")); s.setUserId(u.getId()); s.setExpiresAt(LocalDateTime.now().plusDays(30)); sessions.save(s); return Map.of("token",s.getToken(),"user",safeUser(u)); }
 public User current(HttpServletRequest req){ String token=req.getHeader("X-Auth-Token"); if((token==null||token.isBlank())&&req.getHeader("Authorization")!=null&&req.getHeader("Authorization").startsWith("Bearer ")) token=req.getHeader("Authorization").substring(7); if(token==null||token.isBlank()) throw new SecurityException("Bạn cần đăng nhập"); AuthSession s=sessions.findById(token).orElseThrow(()->new SecurityException("Phiên đăng nhập không hợp lệ")); if(s.getExpiresAt().isBefore(LocalDateTime.now())){sessions.delete(s);throw new SecurityException("Phiên đăng nhập đã hết hạn");} return users.findById(s.getUserId()).orElseThrow(); }
 public User optional(HttpServletRequest req){ try{return current(req);}catch(Exception e){return null;} }
 public void requireRole(User u,String... roles){ Set<String> allowed=new HashSet<>(Arrays.asList(roles)); if(u==null||!allowed.contains(u.getRole())) throw new SecurityException("Bạn không có quyền thực hiện thao tác này"); }
 public Map<String,Object> safeUser(User u){ Map<String,Object> m=new LinkedHashMap<>(); m.put("id",u.getId());m.put("fullName",u.getFullName());m.put("email",u.getEmail());m.put("role",u.getRole());m.put("status",u.getStatus());m.put("phone",u.getPhone());m.put("avatarUrl",u.getAvatarUrl());m.put("bio",u.getBio());m.put("dob",u.getDob());m.put("gender",u.getGender());m.put("schoolName",u.getSchoolName());m.put("facebookUrl",u.getFacebookUrl());m.put("zaloUrl",u.getZaloUrl());m.put("otherSocialUrl",u.getOtherSocialUrl());m.put("homeLat",u.getHomeLat());m.put("homeLng",u.getHomeLng());m.put("matchingRadiusKm",u.getMatchingRadiusKm());m.put("isLookingForRoommate",u.getIsLookingForRoommate()); return m; }
 public void normalizeRole(User u){ if(u.getRole()==null)u.setRole("TENANT"); if(u.getRole().equalsIgnoreCase("manager"))u.setRole("LANDLORD"); if(u.getRole().equalsIgnoreCase("tenant"))u.setRole("TENANT"); u.setRole(u.getRole().toUpperCase(Locale.ROOT)); }
}
