package com.exe201.rrms.service;
import com.exe201.rrms.entity.*; import com.exe201.rrms.repository.*; import com.exe201.rrms.util.GeoUtil; import org.springframework.stereotype.Service; import java.util.*;
@Service public class MatchingService {
 private final MatchingProfileRepository profiles; private final ListingInterestRepository interests; private final UserRepository users; private final AiCompatibilityService ai;
 public MatchingService(MatchingProfileRepository p,ListingInterestRepository i,UserRepository u,AiCompatibilityService ai){profiles=p;interests=i;users=u;this.ai=ai;}
 public List<Map<String,Object>> sameRoom(Long userId,Long listingId){ MatchingProfile me=profiles.findByUserId(userId).orElseThrow(()->new IllegalStateException("Bạn cần hoàn thành hồ sơ Matching trước")); if(!Boolean.TRUE.equals(me.getEnabled()))throw new IllegalStateException("Bạn chưa bật Matching"); List<Map<String,Object>> out=new ArrayList<>(); for(ListingInterest in:interests.findByListingIdAndMatchingEnabledTrue(listingId)){ if(in.getUserId().equals(userId))continue; profiles.findByUserId(in.getUserId()).filter(x->Boolean.TRUE.equals(x.getEnabled())).ifPresent(p->{ Map<String,Object> r=score(me,p); if(((Integer)r.get("score"))>=50)out.add(r);}); } out.sort(Comparator.comparingInt((Map<String,Object>x)->(Integer)x.get("score")).reversed()); return out; }
 public List<Map<String,Object>> nearby(Long userId,int radius){ MatchingProfile me=profiles.findByUserId(userId).orElseThrow(); List<Map<String,Object>> out=new ArrayList<>(); for(MatchingProfile p:profiles.findByEnabledTrue()){ if(p.getUserId().equals(userId))continue; double d=GeoUtil.km(me.getLatitude(),me.getLongitude(),p.getLatitude(),p.getLongitude()); if(d<=radius){Map<String,Object> r=score(me,p);r.put("distanceKm",Math.round(d*10)/10.0); if(((Integer)r.get("score"))>=50)out.add(r);} } out.sort(Comparator.comparingInt((Map<String,Object>x)->(Integer)x.get("score")).reversed()); return out; }
 public Map<String,Object> score(MatchingProfile a,MatchingProfile b){ if(a.getGender()==null||b.getGender()==null||!a.getGender().equalsIgnoreCase(b.getGender())) return Map.of("score",0,"eligible",false,"reason","Khác giới tính theo chính sách Matching hiện tại"); int score=0,max=0; List<String> strengths=new ArrayList<>(), conflicts=new ArrayList<>();
  score+=eq(a.getSleepSchedule(),b.getSleepSchedule(),15,strengths,conflicts,"giờ ngủ");max+=15; score+=nearInt(a.getCleanlinessLevel(),b.getCleanlinessLevel(),15,strengths,conflicts,"mức sạch sẽ");max+=15; score+=eq(a.getSmoking(),b.getSmoking(),15,strengths,conflicts,"hút thuốc");max+=15; score+=budget(a,b,15,strengths,conflicts);max+=15; score+=eq(a.getNoisePreference(),b.getNoisePreference(),10,strengths,conflicts,"mức ồn");max+=10; score+=eq(a.getPets(),b.getPets(),8,strengths,conflicts,"thú cưng");max+=8; score+=eq(a.getGuestFrequency(),b.getGuestFrequency(),7,strengths,conflicts,"khách tới chơi");max+=7; score+=eq(a.getCooking(),b.getCooking(),5,strengths,conflicts,"nấu ăn");max+=5; score+=eq(a.getExpenseStyle(),b.getExpenseStyle(),5,strengths,conflicts,"chia chi phí");max+=5; score+=eq(a.getCommunicationStyle(),b.getCommunicationStyle(),5,strengths,conflicts,"giao tiếp");max+=5; int pct=(int)Math.round(score*100.0/max); User u=users.findById(b.getUserId()).orElse(null); Map<String,Object> r=new LinkedHashMap<>();r.put("userId",b.getUserId());r.put("fullName",u==null?"Người dùng":u.getFullName());r.put("avatarUrl",u==null?null:u.getAvatarUrl());r.put("gender",b.getGender());r.put("schoolName",b.getSchoolName());r.put("score",pct);r.put("strengths",strengths);r.put("conflicts",conflicts);r.put("reason",ai.explain(pct,strengths,conflicts));r.put("facebookUrl",b.getFacebookUrl());r.put("zaloUrl",b.getZaloUrl());r.put("otherSocialUrl",b.getOtherSocialUrl());return r; }
 private int eq(String a,String b,int w,List<String>s,List<String>c,String label){if(a==null||b==null)return w/2;if(a.equalsIgnoreCase(b)){s.add("Tương đồng về "+label);return w;}c.add("Khác nhau về "+label);return w/3;} private int nearInt(Integer a,Integer b,int w,List<String>s,List<String>c,String label){if(a==null||b==null)return w/2;if(Math.abs(a-b)<=1){s.add("Khá tương đồng về "+label);return w;}c.add("Chênh lệch về "+label);return w/3;} private int budget(MatchingProfile a,MatchingProfile b,int w,List<String>s,List<String>c){if(a.getBudgetMax()==null||b.getBudgetMax()==null)return w/2; long amin=a.getBudgetMin()==null?0:a.getBudgetMin(),bmin=b.getBudgetMin()==null?0:b.getBudgetMin(); boolean overlap=Math.max(amin,bmin)<=Math.min(a.getBudgetMax(),b.getBudgetMax());if(overlap){s.add("Ngân sách có vùng giao nhau");return w;}c.add("Ngân sách chênh lệch");return w/4;} private String explain(int p,List<String>s,List<String>c){StringBuilder x=new StringBuilder("Mức tương hợp "+p+"%. "); if(!s.isEmpty())x.append("Điểm phù hợp: ").append(String.join(", ",s)).append(". "); if(!c.isEmpty())x.append("Nên trao đổi trước về: ").append(String.join(", ",c)).append("."); return x.toString();}
}
