package com.exe201.rrms.service;
import com.exe201.rrms.entity.*; import com.exe201.rrms.repository.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import java.net.*; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*;
@Service public class PaymentService {
 private final PaymentRepository payments; private final WalletTransactionRepository txs; private final PackagePlanRepository plans; private final ListingRepository listings; private final NotificationService noti;
 @Value("${unihome.bank.bin:970436}") private String bankBin; @Value("${unihome.bank.account:0000000000}") private String account; @Value("${unihome.bank.name:UNIHOME}") private String accountName;
 public PaymentService(PaymentRepository p,WalletTransactionRepository t,PackagePlanRepository pp,ListingRepository l,NotificationService n){payments=p;txs=t;plans=pp;listings=l;noti=n;}
 public long balance(Long userId){return txs.findByUserIdOrderByCreatedAtDesc(userId).stream().findFirst().map(WalletTransaction::getBalanceAfter).orElse(0L);} public Payment createQr(Long userId,long amount,String type,String refType,Long refId){ Payment p=new Payment();p.setUserId(userId);p.setAmount(amount);p.setType(type);p.setReferenceType(refType);p.setReferenceId(refId);p.setCode("UH"+System.currentTimeMillis()+userId); String info=URLEncoder.encode(p.getCode(),StandardCharsets.UTF_8);p.setQrUrl("https://img.vietqr.io/image/"+bankBin+"-"+account+"-compact2.png?amount="+amount+"&addInfo="+info+"&accountName="+URLEncoder.encode(accountName,StandardCharsets.UTF_8));return payments.save(p);} public void markPaid(Payment p){if("PAID".equals(p.getStatus()))return;p.setStatus("PAID");p.setPaidAt(LocalDateTime.now());payments.save(p);if("WALLET_TOPUP".equals(p.getType())) credit(p.getUserId(),p.getAmount(),"TOPUP",p.getId(),"Nạp tiền qua QR"); if("PACKAGE_DIRECT".equals(p.getType())) activatePackage(p.getUserId(),p.getReferenceId(),p.getPlanId());}
 public WalletTransaction credit(Long uid,long amt,String refType,Long refId,String desc){WalletTransaction t=new WalletTransaction();t.setUserId(uid);t.setType("CREDIT");t.setAmount(amt);t.setBalanceAfter(balance(uid)+amt);t.setReferenceType(refType);t.setReferenceId(refId);t.setDescription(desc);return txs.save(t);} public WalletTransaction debit(Long uid,long amt,String refType,Long refId,String desc){long b=balance(uid);if(b<amt)throw new IllegalStateException("Số dư không đủ");WalletTransaction t=new WalletTransaction();t.setUserId(uid);t.setType("DEBIT");t.setAmount(-amt);t.setBalanceAfter(b-amt);t.setReferenceType(refType);t.setReferenceId(refId);t.setDescription(desc);return txs.save(t);} public void buyWithWallet(Long uid,Long listingId,Long planId){PackagePlan plan=plans.findById(planId).orElseThrow();debit(uid,plan.getPrice(),"PACKAGE",listingId,"Mua "+plan.getName());activatePackage(uid,listingId,planId);} private void activatePackage(Long uid,Long listingId,Long planId){PackagePlan plan=plans.findById(planId).orElseThrow(); Listing li=listings.findById(listingId).orElseThrow(); if(!Objects.equals(li.getLandlordId(),uid))throw new SecurityException("Không phải bài đăng của bạn"); if("BOOST".equals(plan.getCode())){ li.setBoostUntil(LocalDateTime.now().plusDays(Math.max(1,plan.getDurationDays()))); } else { li.setPackageTier(plan.getCode());li.setPackagePriority(plan.getPriority());li.setPackageUntil(LocalDateTime.now().plusDays(plan.getDurationDays()));li.setFreshnessDueAt(li.getPackageUntil().plusDays(15)); } listings.save(li);noti.send(uid,"PACKAGE_ACTIVE","Gói "+plan.getName()+" đã được kích hoạt cho tin #"+listingId,"LISTING",listingId);}
}
